version: "3.8"

services:
  nuxt-app:
    container_name: nuxt-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NITRO_PORT=3000
    command: ["node", ".output/server/index.mjs"]
